# Generated by Django 5.0.7 on 2024-07-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('date_added', models.DateTimeField()),
            ],
        ),
    ]
