# Generated by Django 5.0.7 on 2024-07-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expances',
            name='date_added',
            field=models.DateField(),
        ),
    ]
