# Generated by Django 5.0.7 on 2024-07-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_moneytransactions_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date',
            field=models.DateField(),
        ),
    ]
