# Generated by Django 5.0.7 on 2024-07-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_barcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcodes',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
    ]
